name: cell_info
description: Cell Info Plugin
version: 1.0.0
homepage: https://github.com/onghuisheng/FlutterCellInfo

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.airfore.cell_info
        pluginClass: CellInfoPlugin
      ios:
        pluginClass: CellInfoPlugin
